# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  beta-build:
    macos:
      xcode: "15.3.0" # 適切なXcodeのバージョンを使用してください
    steps:
      # プロジェクトのチェックアウト
      - checkout

      # CocoaPodsのインストール
      - run:
          name: Install CocoaPods
          command: pod install

      # Fastlaneのインストール
      - run:
          name: Install Fastlane
          command: brew install fastlane

      # TestFlightへのベータ版アップロード
      - run:
          name: Build and Upload to TestFlight
          command: fastlane beta # Fastfileに定義した 'beta' レーンを実行

# ワークフローの定義
workflows:
  version: 2
  beta-deployment:
    jobs:
      - beta-build:
          filters:
            branches:
              only:
                - develop # 必要に応じてデプロイしたいブランチ名を指定してください
            tags:
              only: /^v\d+\.\d+\.\d+$/ # タグ名が "v1.2.3" の形式である場合にのみ実行

