version: 2.1

jobs:
  beta-build:
    macos:
      xcode: "15.3.0" # 適切なXcodeのバージョンを使用してください
    steps:
      # プロジェクトのチェックアウト
      - checkout

      # CircleCIが追加したSSHキーを使用する
      - add_ssh_keys:
          fingerprints:
            - "xjItc2nRs118tDyeM4Pmr2ljsafqEYnoUR1de0Vet3g"

      # CocoaPodsのインストール
      - run:
          name: Install CocoaPods
          command: pod install

      # BundlerとFastlaneのインストール
      - run:
          name: Install Bundler and Fastlane
          command: |
            gem install bundler
            bundle install

      # App Store Connect API Key の設定
      - run:
          name: Setup App Store Connect API Key
          command: echo "${APP_STORE_CONNECT_API_KEY_HERBERT_JSON}" | base64 -d > app-store-connect-api-key.json

      # 証明書のインストール
      - run:
          name: Install Certificates
          command: bundle exec fastlane match appstore --api_key_path ./app-store-connect-api-key.json

      # Keychainの設定
      - run:
          name: Setup Keychain
          command: |
            security create-keychain -p "" build.keychain
            security import ./Certificates.p12 -k ~/Library/Keychains/build.keychain -P "certificate_password" -T /usr/bin/codesign
            security list-keychains -d user -s ~/Library/Keychains/build.keychain
            security unlock-keychain -p "" ~/Library/Keychains/build.keychain

      # TestFlightへのベータ版アップロード
      - run:
          name: Build and Upload to TestFlight
          command: fastlane beta # Fastfileに定義した 'beta' レーンを実行

workflows:
  version: 2
  beta-deployment:
    jobs:
      - beta-build:
          filters:
            branches:
              ignore:
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+$/
