version: 2.1

orbs:
  macos: circleci/macos@2
  slack: circleci/slack@4

executors:
  flash_english:
    macos:
      xcode: 15.3.0
    resource_class: macos.m1.medium.gen1

commands:
  set-match-git-basic-authorization:
    steps:
      - run:
          name: Unset git config
          command: git config --global --unset url.ssh://git@github.com.insteadof
      - run:
          name: Set MATCH_GIT_BASIC_AUTHORIZATION
          command: |
            basic_auth="$(echo -n "x-oauth-basic:${GITHUB_TOKEN}" | base64 -d)"
            echo "export MATCH_GIT_BASIC_AUTHORIZATION=\"${basic_auth}\"" >> "${BASH_ENV}"

  setup_app_store_connect_api_key_json:
    parameters:
      value:
        type: string
    steps:
      - run:
          name: Setup app-store-connect-api-key.json
          command: echo "<< parameters.value >>" > ./app-store-connect-api-key.json

jobs:
  deploy:
    executor: flash_english
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "xjItc2nRs118tDyeM4Pmr2ljsafqEYnoUR1de0Vet3g"
      - run:
          name: Set DANGER_GITHUB_BEARER_TOKEN
          command: echo "export DANGER_GITHUB_BEARER_TOKEN=\"${GITHUB_TOKEN}\"" >> "${BASH_ENV}"
      - set-match-git-basic-authorization
      - setup_app_store_connect_api_key_json:
          value: "${APP_STORE_CONNECT_API_KEY_HERBERT_JSON}"
      - run:
          name: Install ncurses (terminfo)
          command: brew install ncurses
      - run:
          name: Add ncurses to path
          command: |
            export TERMINFO=$(brew --prefix ncurses)/share/terminfo
            echo 'export TERMINFO=$(brew --prefix ncurses)/share/terminfo' >> $BASH_ENV
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Install Bundler and Fastlane
          command: |
            gem install bundler -v 2.3.0  # Install stable version of Bundler
            bundle install
      - run:
          name: fastlane deploy
          command: |
            export FASTLANE_DISABLE_COLORS=1
            export FASTLANE_SKIP_TERMINAL_PROMPT=true
            export TERM=dumb  # Prevent terminal control sequences
            bundle exec fastlane deploy

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              ignore:
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+$/
