version: 2.1

jobs:
  beta-build:
    macos:
      xcode: "15.3.0" # 適切なXcodeのバージョンを使用してください
    steps:
      # プロジェクトのチェックアウト
      - checkout

      # CocoaPodsのインストール
      - run:
          name: Install CocoaPods
          command: pod install

      # Fastlaneのインストール
      - run:
          name: Install Fastlane
          command: brew install fastlane

      # TestFlightへのベータ版アップロード
      - run:
          name: Build and Upload to TestFlight
          command: fastlane beta # Fastfileに定義した 'beta' レーンを実行

workflows:
  version: 2
  beta-deployment:
    jobs:
      - beta-build:
          filters:
            branches:
              ignore:
                - develop # developブランチのPushは無視
            tags:
              only: /^v\d+\.\d+\.\d+$/ # タグ名が "v1.2.3" の形式である場合にのみ実行
