version: 2.1

jobs:
  beta-build:
    macos:
      xcode: "15.3.0" # 適切なXcodeのバージョンを使用してください
    steps:
      # プロジェクトのチェックアウト
      - checkout

      # CircleCIが追加したSSHキーを使用する
      - add_ssh_keys:
          fingerprints:
            - "eGwq4Vhw1e+pcGPsqvo4+GqgubDfV79UiJxh0c79fEQ" # CircleCIで表示されているSSHキーのフィンガープリントを設定

      # CocoaPodsのインストール
      - run:
          name: Install CocoaPods
          command: pod install

      # BundlerとFastlaneのインストール
      - run:
          name: Install Bundler and Fastlane
          command: |
            gem install bundler
            bundle install

      # 環境変数の確認
      - run:
          name: Check MATCH_GIT_BASIC_AUTHORIZATION
          command: echo $MATCH_GIT_BASIC_AUTHORIZATION

      # TestFlightへのベータ版アップロード
      - run:
          name: Build and Upload to TestFlight
          command: fastlane beta # Fastfileに定義した 'beta' レーンを実行

workflows:
  version: 2
  beta-deployment:
    jobs:
      - beta-build:
          filters:
            branches:
              ignore:
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+$/
