version: 2.1

jobs:
  beta-build:
    macos:
      xcode: "15.3.0"
    steps:
      - checkout
      - run:
          name: Setup SSH Keys
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Install Fastlane
          command: brew install fastlane
      - run:
          name: Build and Upload to TestFlight
          command: fastlane beta # Fastfileに定義した 'beta' レーンを実行

workflows:
  version: 2
  beta-deployment:
    jobs:
      - beta-build:
          filters:
            branches:
              ignore:
                - develop
            tags:
              only: /^v\d+\.\d+\.\d+$/
