default_platform :ios

platform :ios do
  desc "Upload to Firebase"
  lane :beta do
    unlock_keychain(
      path: "./Library/login.keychain-db", 
      password: ENV["KEYCHAIN_PASSWORD"] 
    )
    match(type: "adhoc", readonly: true)
    gym(scheme: "FlashEnglish")
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      release_notes: "This is a test release!",
      firebase_cli_token: ENV["FIREBASE_APP_DISTRIBUTION_API_TOKEN"] 
    )
  end
end