default_platform(:ios)

platform :ios do
  desc "Upload to Firebase"
  lane :distribute do
    match(type: "adhoc")

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "FlashEnglish.xcworkspace",
      team_id: "L6Q3MJXV23",
      bundle_identifier: "com.masa4y44.FlashEnglish",
      profile_name: "match AdHoc com.masa4y44.FlashEnglish"
    )

    gym(
      scheme: "FlashEnglish",
      verbose: true
    )
    
    firebase_app_distribution(
      app: "1:353282465583:ios:7879b5701a6426a9d1cbda",
      release_notes: "This is a test release!",
      firebase_cli_token: ENV["FIREBASE_APP_DISTRIBUTION_API_TOKEN"]
    )
  end
end
