default_platform(:ios)

platform :ios do
  # Firebase App Distributionへの配信
  desc "Upload to Firebase"
  lane :distribute do
    match(
      type: "adhoc", 
      readonly: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number(app_identifier: "com.masa4y44.FlashEnglish") + 1
    )

    version_number = get_info_plist_value(path: "./FlashEnglish/Resources/Info.plist", key: "CFBundleShortVersionString")
    build_number = get_build_number

    # アプリアイコンにバッジを追加（開発用のデバッグビルドなどで視覚的に識別するため）
    add_badge() 

    # gymを使ってプロジェクトをビルド（`Debug`設定で、Ad-Hoc配信のためのipaを作成）
    gym(
      scheme: "FlashEnglish",
      export_method: "ad-hoc",
      configuration: "Debug"
    )
    
    # Firebase App Distributionにビルドをアップロードしてテスターに配信
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      release_notes: "Betaリリース: #{version_number} (Build: #{build_number})",
      firebase_cli_token: ENV["FIREBASE_APP_DISTRIBUTION_API_TOKEN"],
      testers: ENV["FIREBASE_TESTERS"]
    )
  end

  # App Store Connectへの自動デプロイ
  desc "Build and upload to the App Store"
  lane :upload_appstore do
    match(
      type: "appstore", 
      readonly: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number(app_identifier: "com.masa4y44.FlashEnglish") + 1
    )

    # gymを使ってプロジェクトをビルド（`Release`設定で、App Store用にビルド）
    gym(
      scheme: "FlashEnglish",
      export_method: "app-store",
      configuration: "Release"
    )
    
    # App Store Connectにアプリをアップロード
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      automatic_release: false,
      precheck_include_in_app_purchases: false # アプリ内課金チェックをスキップ
    )
  end
end