name: comment hook

on:
  issue_comment:
    types: [created]

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # You can specify your version here

      # Step 3: Install dependencies (Fastlane)
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      # Step 4: Check if the comment contains "distribute beta"
      - name: Check if comment contains "distribute beta"
        id: check_comment
        run: |
          PAYLOAD=$(cat "$GITHUB_EVENT_PATH")
          COMMENT=$(echo "$PAYLOAD" | jq -r '.comment.body')
          if [[ "$COMMENT" =~ "distribute beta" ]]; then
            echo "Distribute beta triggered."
            echo "::set-output name=run_beta::true"
          else
            echo "No beta distribution trigger found. Exiting."
            echo "::set-output name=run_beta::false"
            exit 0
          fi

      # Step 5: Run Fastlane beta if the comment contains the trigger
      - name: Run Fastlane beta
        if: steps.check_comment.outputs.run_beta == 'true'
        run: |
          bundle exec fastlane beta
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_APP_DISTRIBUTION_API_TOKEN: ${{ secrets.FIREBASE_APP_DISTRIBUTION_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
