name: PR Static Analysis and Lint

on:
  pull_request:
    types: [opened, synchronize]  # Trigger when a PR is created or updated

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Decrypt GoogleService-Info.plist
        run: |
          mkdir -p FlashEnglish/Resources/Firebase
          echo "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > FlashEnglish/Resources/Firebase/GoogleService-Info.plist
        env:
          GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}

      - name: Restore Gem Cache
        uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: v1-dependencies-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v1-dependencies-${{ runner.os }}-gems-

      - name: Install Bundler and dependencies
        run: |
          gem install bundler -v "$(tail -n 1 Gemfile.lock | sed -r 's/ //g')" -N
          bundle config set path './vendor/bundle'
          bundle install

      - name: Save Gem Cache
        uses: actions/cache@v2
        with:
          path: ./vendor/bundle
          key: v1-dependencies-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install Rosetta (For M1 Macs if needed)
        run: |
          softwareupdate --install-rosetta --agree-to-license

      - name: Run Danger
        run: bundle exec danger
        env:
          DANGER_GITHUB_BEARER_TOKEN: ${{ secrets.DANGER_GITHUB_BEARER_TOKEN }}

      - name: Run Fastlane Test
        run: bundle exec fastlane test
