name: PR Static Analysis and Lint

on:
  pull_request:
    types: [opened, synchronize]  # PRが作成されたとき、または新しいコミットがあったときにトリガー

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - checkout
      - prepare
      - run:
          name: Set DANGER_GITHUB_BEARER_TOKEN
          command: echo "export DANGER_GITHUB_BEARER_TOKEN=\"${GITHUB_TOKEN}\"" >> "${BASH_ENV}"
      - danger
      - run:
          name: Fastlane test
          command: bundle exec fastlane test
      - store_test_results:
          path: "fastlane/test_output"
